# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.classification_api import ClassificationApi


class TestClassificationApi(unittest.TestCase):
    """ ClassificationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.classification_api.ClassificationApi()

    def tearDown(self):
        pass

    def test_classify(self):
        """
        Test case for classify

        Determine a document's classification(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
